Repository astrocamp/20th-BuyBuddy, pull requests merged in 2025-09, with the labels that each got.

#118 fix #117 : 解決groups/new 欄位互相覆蓋資料 & 刪除團購功能失效
  groups/templates/groups/manage.html
  groups/views.py
Labels: 已處理 Gemini 建議, 可以合併的

#132 feat#131: 加入團購新增判段是否達標邏輯
  groups/services/group_services.py
Labels: 已處理 Gemini 建議

#126 feat#112: 富文本串接
  .gitignore
  BuyBuddy/settings.py
  BuyBuddy/urls.py
  groups/forms.py
  groups/migrations/0010_alter_group_description.py
  groups/models.py
  groups/templates/groups/detail.html
  groups/templates/groups/manage.html
  groups/templates/groups/member_edit.html
  groups/templates/groups/new.html
  groups/urls.py
  groups/views.py
  products/migrations/0005_alter_product_description.py
  products/models.py
  pyproject.toml
  src/scripts/app.js
  src/scripts/tinymceCsrf.js
  templates/layouts/default.html
  uv.lock
Labels: 已處理 Gemini 建議, 可以合併的, 衝突啦老師

#128 feat#127: celery排程檢查deadline
  .env.example
  .gitignore
  BuyBuddy/celery_app.py
  groups/tasks.py
  pyproject.toml
  uv.lock
Labels: 已處理 Gemini 建議, 可以合併的, 衝突啦老師

#153 style#138: 優化我跟團/開團的訂單樣式(RWD)
  .gitignore
  groups/forms.py
  groups/models.py
  orders/models.py
  orders/templates/orders/my_orders/list.html
  orders/templates/orders/my_orders/list_columns.html
  orders/templates/orders/owned_orders/buyers_list.html
  orders/templates/orders/owned_orders/list.html
  orders/templates/orders/owned_orders/list_columns.html
  orders/templates/orders/owned_orders/navbar.html
  orders/templates/orders/owned_orders/section.html
  orders/templates/orders/shared/navbar.html
  orders/urls.py
  orders/views.py
  src/styles/style.css
Labels: 已處理 Gemini 建議, 可以合併的

#170 feat#155: 首頁、導覽列樣式更新
  groups/templates/groups/shared/group_card.html
  orders/models.py
  orders/templates/orders/shared/navbar.html
  pages/templates/pages/home.html
  public/asset/buddy_1.svg
  public/asset/buddy_2.svg
  public/assets/avatar_default.svg
  public/assets/google.png
  public/assets/hero-pic.jpg
  public/assets/line.png
  public/assets/logo-white.svg
  public/assets/logo.svg
  src/scripts/app.js
  src/scripts/navigation.js
  src/styles/style.css
  templates/layouts/default.html
  templates/shared/back_to_top_btn.html
  templates/shared/footer.html
  templates/shared/hum_nav.html
  templates/shared/navbar.html
  templates/shared/notifications_dropdown.html
  users/templates/users/new.html
  users/templates/users/sessions_new.html
  users/templates/users/shared/profiles.html
  users/templates/users/shared/social_login_buttons.html
Labels: 已處理 Gemini 建議, 這是要先合併的尾巴分支 !!!

#172 feat: groups UI優化與頁面整合
  BuyBuddy/settings.py
  groups/forms.py
  groups/services/group_services.py
  groups/templates/groups/detail.html
  groups/templates/groups/manage_edit.html
  groups/templates/groups/new.html
  groups/templates/groups/product_form.html
  groups/templates/groups/shared/htmx_response.html
  groups/urls.py
  groups/views.py
  src/scripts/app.js
  src/scripts/imagePreview.js
  src/scripts/productFormset.js
  src/scripts/tinymceCsrf.js
  templates/shared/tab_group.html
  users/forms.py
  users/templates/users/edit.html
  users/templates/users/shared/profiles_edit.html
Labels: 已處理 Gemini 建議

#173 feat#135: 新增 Google 第三方登入功能
  BuyBuddy/settings.py
  BuyBuddy/urls.py
  pyproject.toml
  users/adapters.py
  users/templates/users/shared/social_login_buttons.html
  uv.lock
Labels: 已處理 Gemini 建議

#190 fix#186: 修正未成團參團紀錄必須篩掉有 deleted_at 的紀錄
  orders/views.py
Labels: 這是要先合併的尾巴分支 !!!

#198 feat#185: 已成團的跟團者資訊輸出 excel
  BuyBuddy/settings.py
  groups/templates/groups/detail.html
  orders/exports.py
  orders/templates/orders/owned_orders/buyers_list.html
  orders/urls.py
  orders/utils.py
  orders/views.py
  pyproject.toml
  src/styles/style.css
  templates/shared/navbar.html
  uv.lock
Labels: 已處理 Gemini 建議

#217 ref#215: 第三方登入邏輯修正及優化
  BuyBuddy/settings.py
  src/scripts/app.js
  src/scripts/googleAuth.js
  users/adapters.py
  users/templates/users/shared/social_login_buttons.html
  users/urls.py
  users/views.py
Labels: 已處理 Gemini 建議

#245 fix#239: Google第三方登入彈窗與導向問題
  BuyBuddy/settings.py
  src/scripts/googleAuth.js
  users/templates/users/shared/social_login_buttons.html
  users/views.py
Labels: 已處理 Gemini 建議

#247 fix246: bug修正
  BuyBuddy/settings.py
  BuyBuddy/urls.py
  groups/forms.py
  groups/services/group_services.py
  groups/templates/groups/new.html
  groups/views.py
  pages/views.py
  products/templates/products/index.html
  products/templates/products/product_detail.html
  products/urls.py
  products/views.py
  public/scripts/app.js
  public/styles/style.css
  sales/__init__.py
  sales/admin.py
  sales/apps.py
  sales/migrations/__init__.py
  sales/models.py
  sales/templates/sales/index.html
  sales/tests.py
  sales/urls.py
  sales/views.py
  status/__init__.py
  status/admin.py
  status/apps.py
  status/migrations/__init__.py
  status/models.py
  status/templates/status/ended_list.html
  status/templates/status/in_progress_list.html
  status/templates/status/index.html
  status/tests.py
  status/urls.py
  status/views.py
Labels: 已處理 Gemini 建議
