Repository astrocamp/20th-BuyBuddy, pull requests merged in 2025-08, with the labels that each got.

#67 issue#57 fix: 處理 N+1 查詢問題
  products/templates/products/product_detail.html
  products/views.py
Labels: 首次 PR

#74 issue#49 新增團購編輯及刪除功能
  BuyBuddy/settings.py
  groups/forms.py
  groups/templates/groups/create_group.html
  groups/templates/groups/edit_group.html
  groups/templates/groups/index.html
  groups/templates/groups/read_group.html
  groups/templates/groups/upload_img.html
  groups/urls.py
  groups/views.py
  src/scripts/app.js
  src/scripts/create_group.js
  src/scripts/validators.js
Labels: 首次 PR

#75 issue#56 新增 產品新增頁面
  groups/templates/groups/edit_group.html
  products/forms.py
  products/templates/products/product_create.html
  products/urls.py
  products/views.py
Labels: 首次 PR

#84 fix#77: 修正通知畫面閃爍問題
  src/styles/style.css
  templates/shared/notifications_dropdown.html
Labels: 已處理 Gemini 建議

#90 issue#86: 團購編輯裡新增產品編輯
  groups/templates/groups/edit_group.html
  groups/views.py
Labels: feat
